Make sure log.exception("...") with no exception doesn't crash logview.
It used to cause

  AttributeError: 'NoneType' object has no attribute '__name__'

in _logbar_mako line 187.